apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  serviceName: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:9.4.3
          ports:
            - containerPort: 3000
              name: grafana
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
            - name: grafana-config-provisioning
              mountPath: /etc/grafana/provisioning
            - name: grafana-config-dashboards
              mountPath: /tmp/dashboards
      volumes:
        - name: grafana-config-provisioning
          configMap:
            name: grafana-config
            items:
              - key: provisioning-dashboards-default.yaml
                path: dashboards/default.yaml
              - key: provisioning-datasources-datasource.yaml
                path: datasources/datasource.yaml
        - name: grafana-config-dashboards
          configMap:
            name: grafana-config
            items:
              - key: dashboards-dashboard.json
                path: dashboard.json
  volumeClaimTemplates:
    - metadata:
        name: grafana-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
